/**
 * AILearningPath Model
 * Represents a personalized learning path generated by AI.
 */
const mongoose = require('mongoose');

const aiLearningPathSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User is required']
  },
  careerGoal: {
    type: String,
    required: [true, 'Career goal is required'],
    trim: true
  },
  currentSkills: [{
    type: String,
    trim: true
  }],
  targetSkills: [{
    type: String,
    trim: true
  }],
  availableHoursPerDay: {
    type: Number
  },
  deadline: {
    type: Date
  },
  difficultyPreference: {
    type: String,
    enum: {
      values: ['beginner', 'intermediate', 'advanced', 'mixed'],
      message: '{VALUE} is not a valid difficulty preference'
    }
  },
  roadmap: {
    phases: [{
      name: String,
      duration: String,
      topics: [{
        name: String,
        description: String,
        priority: {
          type: String,
          enum: ['must_learn', 'should_learn', 'nice_to_have']
        },
        estimatedHours: Number,
        resources: [String],
        relatedCourses: [{
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Course'
        }]
      }]
    }]
  },
  weeklyMilestones: [{
    week: Number,
    goals: [String],
    checkpoints: [String]
  }],
  dailySchedule: {
    recommended: [{
      day: String,
      topics: [String],
      duration: Number
    }]
  },
  revisionPlan: {
    intervals: [String],
    weakTopicFocus: [String]
  },
  practiceRecommendations: [{
    type: String
  }],
  roadmapUrl: {
    type: String
  },
  roadmapSearchUrl: {
    type: String
  },
  status: {
    type: String,
    enum: {
      values: ['active', 'completed', 'abandoned', 'regenerated'],
      message: '{VALUE} is not a valid status'
    },
    default: 'active'
  },
  progress: {
    type: Number,
    default: 0,
    min: [0, 'Progress cannot be less than 0'],
    max: [100, 'Progress cannot be more than 100']
  },
  promptVersion: {
    type: String,
    required: [true, 'Prompt version is required']
  },
  model: {
    type: String,
    required: [true, 'Model is required']
  },
  generatedAt: {
    type: Date,
    default: Date.now
  },
  regeneratedFrom: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'AILearningPath'
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Indexes
aiLearningPathSchema.index({ user: 1, status: 1, generatedAt: -1 });
aiLearningPathSchema.index({ user: 1, generatedAt: -1 });

// Statics
aiLearningPathSchema.statics.findActive = function(userId) {
  return this.findOne({ user: userId, status: 'active' }).sort({ generatedAt: -1 });
};

aiLearningPathSchema.statics.findHistory = function(userId) {
  return this.find({ user: userId }).sort({ generatedAt: -1 });
};

module.exports = mongoose.model('AILearningPath', aiLearningPathSchema);
